import streamlit as st
import requests
import datetime

BASE_URL = "http://localhost:8000"  # Backend endpoint

# ---------- Page Configuration ---------- #
st.set_page_config(
    page_title="🌍 Travel Planner | Agentic AI",
    page_icon="🌍",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------- Header Section ---------- #
st.markdown("""
    <style>
        .main-title {font-size: 2.5em; font-weight: 700; margin-bottom: 0.2em;}
        .sub-header {font-size: 1.2em; color: gray; margin-bottom: 2em;}
    </style>
""", unsafe_allow_html=True)

st.markdown("<div class='main-title'>🌍 AI Travel Planner</div>", unsafe_allow_html=True)
st.markdown("<div class='sub-header'>Your personal AI travel assistant for planning smart, detailed trips.</div>", unsafe_allow_html=True)

# ---------- Chat Section ---------- #
with st.container():
    st.subheader("✈️ Tell me your dream destination and duration")
    with st.form(key="query_form", clear_on_submit=True):
        user_input = st.text_input(
            label="Trip Planner Input",
            placeholder="e.g. Plan a 5-day trip to Goa including hotels and budget breakdown",
            label_visibility="collapsed"
        )
        submit_button = st.form_submit_button("Generate Plan")

# ---------- API Call and Response Handling ---------- #
if submit_button and user_input.strip():
    with st.spinner("Generating your itinerary..."):
        try:
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload)

            if response.status_code == 200:
                answer = response.json().get("answer", "No answer returned.")
                generated_time = datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')

                with st.expander("📋 Trip Overview", expanded=True):
                    st.markdown(f"""
                        ### 🧾 Itinerary Generated On: `{generated_time}`
                        #### 🤖 Generated by Atriyo's AI Travel Agent
                        ---
                        {answer}
                        ---
                        ⚠️ *Please verify all information, especially prices and schedules, before your trip.*
                    """)
            else:
                st.error(f"🚫 Bot failed to respond: {response.text}")

        except Exception as e:
            st.error(f"❌ An error occurred: {e}")

# ---------- Footer ---------- #
st.markdown("""
---
<center>Made with ❤️ using Agentic AI | Powered by OpenAI & Streamlit</center>
""", unsafe_allow_html=True)
